/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserMapRouteImport } from './routes/user/map'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as SetupPasswordRouteImport } from './routes/setup/password'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements/$id'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as UserSkinsIndexRouteImport } from './routes/user/skins/index'
import { Route as UserProfilesIndexRouteImport } from './routes/user/profiles/index'
import { Route as UserProfileIndexRouteImport } from './routes/user/profile/index'
import { Route as UserMyIndexRouteImport } from './routes/user/my/index'
import { Route as UserMyTitlesIndexRouteImport } from './routes/user/my-titles/index'
import { Route as UserIssuesIndexRouteImport } from './routes/user/issues/index'
import { Route as UserGameInfoIndexRouteImport } from './routes/user/game-info/index'
import { Route as UserCommandsIndexRouteImport } from './routes/user/commands/index'
import { Route as UserChatIndexRouteImport } from './routes/user/chat/index'
import { Route as UserCapesIndexRouteImport } from './routes/user/capes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTitlesIndexRouteImport } from './routes/admin/titles/index'
import { Route as AdminSkinsIndexRouteImport } from './routes/admin/skins/index'
import { Route as AdminServersIndexRouteImport } from './routes/admin/servers/index'
import { Route as AdminServerLoadIndexRouteImport } from './routes/admin/server-load/index'
import { Route as AdminPluginCredentialsIndexRouteImport } from './routes/admin/plugin-credentials/index'
import { Route as AdminIssuesIndexRouteImport } from './routes/admin/issues/index'
import { Route as AdminIssueTypesIndexRouteImport } from './routes/admin/issue-types/index'
import { Route as AdminGameProfilesIndexRouteImport } from './routes/admin/game-profiles/index'
import { Route as AdminCapesIndexRouteImport } from './routes/admin/capes/index'
import { Route as AdminAnnouncementsIndexRouteImport } from './routes/admin/announcements/index'
import { Route as AdminAnnouncementSchedulesIndexRouteImport } from './routes/admin/announcement-schedules/index'
import { Route as AdminAchievementsIndexRouteImport } from './routes/admin/achievements/index'
import { Route as UserIssuesIssueIdRouteImport } from './routes/user/issues/$issueId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminSkinsCreateRouteImport } from './routes/admin/skins/create'
import { Route as AdminSkinsSkinIdRouteImport } from './routes/admin/skins/$skinId'
import { Route as AdminPluginCredentialsCredentialIdRouteImport } from './routes/admin/plugin-credentials/$credentialId'
import { Route as AdminIssuesIssueIdRouteImport } from './routes/admin/issues/$issueId'
import { Route as AdminGameProfilesProfileIdRouteImport } from './routes/admin/game-profiles/$profileId'
import { Route as AdminCapesCreateRouteImport } from './routes/admin/capes/create'
import { Route as AdminCapesCapeIdRouteImport } from './routes/admin/capes/$capeId'
import { Route as AdminAnnouncementsCreateRouteImport } from './routes/admin/announcements/create'
import { Route as AdminAnnouncementsAnnouncementIdRouteImport } from './routes/admin/announcements/$announcementId'
import { Route as AdminAchievementsCreateRouteImport } from './routes/admin/achievements/create'
import { Route as AdminAchievementsAchievementIdRouteImport } from './routes/admin/achievements/$achievementId'
import { Route as AdminMessagesCommandsIndexRouteImport } from './routes/admin/messages/commands/index'
import { Route as AdminMessagesChatIndexRouteImport } from './routes/admin/messages/chat/index'
import { Route as AdminUsersUserIdGameProfilesRouteImport } from './routes/admin/users/$userId_.game-profiles'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserMapRoute = UserMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SetupRoute,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/announcements/$id',
  path: '/announcements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const UserSkinsIndexRoute = UserSkinsIndexRouteImport.update({
  id: '/skins/',
  path: '/skins/',
  getParentRoute: () => UserRoute,
} as any)
const UserProfilesIndexRoute = UserProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => UserRoute,
} as any)
const UserMyIndexRoute = UserMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => UserRoute,
} as any)
const UserMyTitlesIndexRoute = UserMyTitlesIndexRouteImport.update({
  id: '/my-titles/',
  path: '/my-titles/',
  getParentRoute: () => UserRoute,
} as any)
const UserIssuesIndexRoute = UserIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => UserRoute,
} as any)
const UserGameInfoIndexRoute = UserGameInfoIndexRouteImport.update({
  id: '/game-info/',
  path: '/game-info/',
  getParentRoute: () => UserRoute,
} as any)
const UserCommandsIndexRoute = UserCommandsIndexRouteImport.update({
  id: '/commands/',
  path: '/commands/',
  getParentRoute: () => UserRoute,
} as any)
const UserChatIndexRoute = UserChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => UserRoute,
} as any)
const UserCapesIndexRoute = UserCapesIndexRouteImport.update({
  id: '/capes/',
  path: '/capes/',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTitlesIndexRoute = AdminTitlesIndexRouteImport.update({
  id: '/titles/',
  path: '/titles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkinsIndexRoute = AdminSkinsIndexRouteImport.update({
  id: '/skins/',
  path: '/skins/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServersIndexRoute = AdminServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServerLoadIndexRoute = AdminServerLoadIndexRouteImport.update({
  id: '/server-load/',
  path: '/server-load/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPluginCredentialsIndexRoute =
  AdminPluginCredentialsIndexRouteImport.update({
    id: '/plugin-credentials/',
    path: '/plugin-credentials/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIssuesIndexRoute = AdminIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssueTypesIndexRoute = AdminIssueTypesIndexRouteImport.update({
  id: '/issue-types/',
  path: '/issue-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameProfilesIndexRoute = AdminGameProfilesIndexRouteImport.update({
  id: '/game-profiles/',
  path: '/game-profiles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapesIndexRoute = AdminCapesIndexRouteImport.update({
  id: '/capes/',
  path: '/capes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementSchedulesIndexRoute =
  AdminAnnouncementSchedulesIndexRouteImport.update({
    id: '/announcement-schedules/',
    path: '/announcement-schedules/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAchievementsIndexRoute = AdminAchievementsIndexRouteImport.update({
  id: '/achievements/',
  path: '/achievements/',
  getParentRoute: () => AdminRoute,
} as any)
const UserIssuesIssueIdRoute = UserIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkinsCreateRoute = AdminSkinsCreateRouteImport.update({
  id: '/skins/create',
  path: '/skins/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkinsSkinIdRoute = AdminSkinsSkinIdRouteImport.update({
  id: '/skins/$skinId',
  path: '/skins/$skinId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPluginCredentialsCredentialIdRoute =
  AdminPluginCredentialsCredentialIdRouteImport.update({
    id: '/plugin-credentials/$credentialId',
    path: '/plugin-credentials/$credentialId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIssuesIssueIdRoute = AdminIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameProfilesProfileIdRoute =
  AdminGameProfilesProfileIdRouteImport.update({
    id: '/game-profiles/$profileId',
    path: '/game-profiles/$profileId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCapesCreateRoute = AdminCapesCreateRouteImport.update({
  id: '/capes/create',
  path: '/capes/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapesCapeIdRoute = AdminCapesCapeIdRouteImport.update({
  id: '/capes/$capeId',
  path: '/capes/$capeId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsCreateRoute =
  AdminAnnouncementsCreateRouteImport.update({
    id: '/announcements/create',
    path: '/announcements/create',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAnnouncementsAnnouncementIdRoute =
  AdminAnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAchievementsCreateRoute = AdminAchievementsCreateRouteImport.update({
  id: '/achievements/create',
  path: '/achievements/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAchievementsAchievementIdRoute =
  AdminAchievementsAchievementIdRouteImport.update({
    id: '/achievements/$achievementId',
    path: '/achievements/$achievementId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMessagesCommandsIndexRoute =
  AdminMessagesCommandsIndexRouteImport.update({
    id: '/messages/commands/',
    path: '/messages/commands/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMessagesChatIndexRoute = AdminMessagesChatIndexRouteImport.update({
  id: '/messages/chat/',
  path: '/messages/chat/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdGameProfilesRoute =
  AdminUsersUserIdGameProfilesRouteImport.update({
    id: '/users/$userId_/game-profiles',
    path: '/users/$userId/game-profiles',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/setup': typeof SetupRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/setup/password': typeof SetupPasswordRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/map': typeof UserMapRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/achievements/$achievementId': typeof AdminAchievementsAchievementIdRoute
  '/admin/achievements/create': typeof AdminAchievementsCreateRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/announcements/create': typeof AdminAnnouncementsCreateRoute
  '/admin/capes/$capeId': typeof AdminCapesCapeIdRoute
  '/admin/capes/create': typeof AdminCapesCreateRoute
  '/admin/game-profiles/$profileId': typeof AdminGameProfilesProfileIdRoute
  '/admin/issues/$issueId': typeof AdminIssuesIssueIdRoute
  '/admin/plugin-credentials/$credentialId': typeof AdminPluginCredentialsCredentialIdRoute
  '/admin/skins/$skinId': typeof AdminSkinsSkinIdRoute
  '/admin/skins/create': typeof AdminSkinsCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/user/issues/$issueId': typeof UserIssuesIssueIdRoute
  '/admin/achievements/': typeof AdminAchievementsIndexRoute
  '/admin/announcement-schedules/': typeof AdminAnnouncementSchedulesIndexRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/capes/': typeof AdminCapesIndexRoute
  '/admin/game-profiles/': typeof AdminGameProfilesIndexRoute
  '/admin/issue-types/': typeof AdminIssueTypesIndexRoute
  '/admin/issues/': typeof AdminIssuesIndexRoute
  '/admin/plugin-credentials/': typeof AdminPluginCredentialsIndexRoute
  '/admin/server-load/': typeof AdminServerLoadIndexRoute
  '/admin/servers/': typeof AdminServersIndexRoute
  '/admin/skins/': typeof AdminSkinsIndexRoute
  '/admin/titles/': typeof AdminTitlesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/user/capes/': typeof UserCapesIndexRoute
  '/user/chat/': typeof UserChatIndexRoute
  '/user/commands/': typeof UserCommandsIndexRoute
  '/user/game-info/': typeof UserGameInfoIndexRoute
  '/user/issues/': typeof UserIssuesIndexRoute
  '/user/my-titles/': typeof UserMyTitlesIndexRoute
  '/user/my/': typeof UserMyIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
  '/user/profiles/': typeof UserProfilesIndexRoute
  '/user/skins/': typeof UserSkinsIndexRoute
  '/admin/users/$userId/game-profiles': typeof AdminUsersUserIdGameProfilesRoute
  '/admin/messages/chat/': typeof AdminMessagesChatIndexRoute
  '/admin/messages/commands/': typeof AdminMessagesCommandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/setup': typeof SetupRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/setup/password': typeof SetupPasswordRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/map': typeof UserMapRoute
  '/admin': typeof AdminIndexRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/achievements/$achievementId': typeof AdminAchievementsAchievementIdRoute
  '/admin/achievements/create': typeof AdminAchievementsCreateRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/announcements/create': typeof AdminAnnouncementsCreateRoute
  '/admin/capes/$capeId': typeof AdminCapesCapeIdRoute
  '/admin/capes/create': typeof AdminCapesCreateRoute
  '/admin/game-profiles/$profileId': typeof AdminGameProfilesProfileIdRoute
  '/admin/issues/$issueId': typeof AdminIssuesIssueIdRoute
  '/admin/plugin-credentials/$credentialId': typeof AdminPluginCredentialsCredentialIdRoute
  '/admin/skins/$skinId': typeof AdminSkinsSkinIdRoute
  '/admin/skins/create': typeof AdminSkinsCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/user/issues/$issueId': typeof UserIssuesIssueIdRoute
  '/admin/achievements': typeof AdminAchievementsIndexRoute
  '/admin/announcement-schedules': typeof AdminAnnouncementSchedulesIndexRoute
  '/admin/announcements': typeof AdminAnnouncementsIndexRoute
  '/admin/capes': typeof AdminCapesIndexRoute
  '/admin/game-profiles': typeof AdminGameProfilesIndexRoute
  '/admin/issue-types': typeof AdminIssueTypesIndexRoute
  '/admin/issues': typeof AdminIssuesIndexRoute
  '/admin/plugin-credentials': typeof AdminPluginCredentialsIndexRoute
  '/admin/server-load': typeof AdminServerLoadIndexRoute
  '/admin/servers': typeof AdminServersIndexRoute
  '/admin/skins': typeof AdminSkinsIndexRoute
  '/admin/titles': typeof AdminTitlesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/user/capes': typeof UserCapesIndexRoute
  '/user/chat': typeof UserChatIndexRoute
  '/user/commands': typeof UserCommandsIndexRoute
  '/user/game-info': typeof UserGameInfoIndexRoute
  '/user/issues': typeof UserIssuesIndexRoute
  '/user/my-titles': typeof UserMyTitlesIndexRoute
  '/user/my': typeof UserMyIndexRoute
  '/user/profile': typeof UserProfileIndexRoute
  '/user/profiles': typeof UserProfilesIndexRoute
  '/user/skins': typeof UserSkinsIndexRoute
  '/admin/users/$userId/game-profiles': typeof AdminUsersUserIdGameProfilesRoute
  '/admin/messages/chat': typeof AdminMessagesChatIndexRoute
  '/admin/messages/commands': typeof AdminMessagesCommandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/rules': typeof RulesRoute
  '/setup': typeof SetupRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/setup/password': typeof SetupPasswordRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/map': typeof UserMapRoute
  '/admin/': typeof AdminIndexRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/achievements/$achievementId': typeof AdminAchievementsAchievementIdRoute
  '/admin/achievements/create': typeof AdminAchievementsCreateRoute
  '/admin/announcements/$announcementId': typeof AdminAnnouncementsAnnouncementIdRoute
  '/admin/announcements/create': typeof AdminAnnouncementsCreateRoute
  '/admin/capes/$capeId': typeof AdminCapesCapeIdRoute
  '/admin/capes/create': typeof AdminCapesCreateRoute
  '/admin/game-profiles/$profileId': typeof AdminGameProfilesProfileIdRoute
  '/admin/issues/$issueId': typeof AdminIssuesIssueIdRoute
  '/admin/plugin-credentials/$credentialId': typeof AdminPluginCredentialsCredentialIdRoute
  '/admin/skins/$skinId': typeof AdminSkinsSkinIdRoute
  '/admin/skins/create': typeof AdminSkinsCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/user/issues/$issueId': typeof UserIssuesIssueIdRoute
  '/admin/achievements/': typeof AdminAchievementsIndexRoute
  '/admin/announcement-schedules/': typeof AdminAnnouncementSchedulesIndexRoute
  '/admin/announcements/': typeof AdminAnnouncementsIndexRoute
  '/admin/capes/': typeof AdminCapesIndexRoute
  '/admin/game-profiles/': typeof AdminGameProfilesIndexRoute
  '/admin/issue-types/': typeof AdminIssueTypesIndexRoute
  '/admin/issues/': typeof AdminIssuesIndexRoute
  '/admin/plugin-credentials/': typeof AdminPluginCredentialsIndexRoute
  '/admin/server-load/': typeof AdminServerLoadIndexRoute
  '/admin/servers/': typeof AdminServersIndexRoute
  '/admin/skins/': typeof AdminSkinsIndexRoute
  '/admin/titles/': typeof AdminTitlesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/user/capes/': typeof UserCapesIndexRoute
  '/user/chat/': typeof UserChatIndexRoute
  '/user/commands/': typeof UserCommandsIndexRoute
  '/user/game-info/': typeof UserGameInfoIndexRoute
  '/user/issues/': typeof UserIssuesIndexRoute
  '/user/my-titles/': typeof UserMyTitlesIndexRoute
  '/user/my/': typeof UserMyIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
  '/user/profiles/': typeof UserProfilesIndexRoute
  '/user/skins/': typeof UserSkinsIndexRoute
  '/admin/users/$userId_/game-profiles': typeof AdminUsersUserIdGameProfilesRoute
  '/admin/messages/chat/': typeof AdminMessagesChatIndexRoute
  '/admin/messages/commands/': typeof AdminMessagesCommandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/callback'
    | '/login'
    | '/rules'
    | '/setup'
    | '/user'
    | '/admin/dashboard'
    | '/announcements/$id'
    | '/setup/password'
    | '/user/dashboard'
    | '/user/map'
    | '/admin/'
    | '/announcements/'
    | '/user/'
    | '/admin/achievements/$achievementId'
    | '/admin/achievements/create'
    | '/admin/announcements/$announcementId'
    | '/admin/announcements/create'
    | '/admin/capes/$capeId'
    | '/admin/capes/create'
    | '/admin/game-profiles/$profileId'
    | '/admin/issues/$issueId'
    | '/admin/plugin-credentials/$credentialId'
    | '/admin/skins/$skinId'
    | '/admin/skins/create'
    | '/admin/users/$userId'
    | '/user/issues/$issueId'
    | '/admin/achievements/'
    | '/admin/announcement-schedules/'
    | '/admin/announcements/'
    | '/admin/capes/'
    | '/admin/game-profiles/'
    | '/admin/issue-types/'
    | '/admin/issues/'
    | '/admin/plugin-credentials/'
    | '/admin/server-load/'
    | '/admin/servers/'
    | '/admin/skins/'
    | '/admin/titles/'
    | '/admin/users/'
    | '/user/capes/'
    | '/user/chat/'
    | '/user/commands/'
    | '/user/game-info/'
    | '/user/issues/'
    | '/user/my-titles/'
    | '/user/my/'
    | '/user/profile/'
    | '/user/profiles/'
    | '/user/skins/'
    | '/admin/users/$userId/game-profiles'
    | '/admin/messages/chat/'
    | '/admin/messages/commands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/callback'
    | '/login'
    | '/rules'
    | '/setup'
    | '/admin/dashboard'
    | '/announcements/$id'
    | '/setup/password'
    | '/user/dashboard'
    | '/user/map'
    | '/admin'
    | '/announcements'
    | '/user'
    | '/admin/achievements/$achievementId'
    | '/admin/achievements/create'
    | '/admin/announcements/$announcementId'
    | '/admin/announcements/create'
    | '/admin/capes/$capeId'
    | '/admin/capes/create'
    | '/admin/game-profiles/$profileId'
    | '/admin/issues/$issueId'
    | '/admin/plugin-credentials/$credentialId'
    | '/admin/skins/$skinId'
    | '/admin/skins/create'
    | '/admin/users/$userId'
    | '/user/issues/$issueId'
    | '/admin/achievements'
    | '/admin/announcement-schedules'
    | '/admin/announcements'
    | '/admin/capes'
    | '/admin/game-profiles'
    | '/admin/issue-types'
    | '/admin/issues'
    | '/admin/plugin-credentials'
    | '/admin/server-load'
    | '/admin/servers'
    | '/admin/skins'
    | '/admin/titles'
    | '/admin/users'
    | '/user/capes'
    | '/user/chat'
    | '/user/commands'
    | '/user/game-info'
    | '/user/issues'
    | '/user/my-titles'
    | '/user/my'
    | '/user/profile'
    | '/user/profiles'
    | '/user/skins'
    | '/admin/users/$userId/game-profiles'
    | '/admin/messages/chat'
    | '/admin/messages/commands'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/callback'
    | '/login'
    | '/rules'
    | '/setup'
    | '/user'
    | '/admin/dashboard'
    | '/announcements/$id'
    | '/setup/password'
    | '/user/dashboard'
    | '/user/map'
    | '/admin/'
    | '/announcements/'
    | '/user/'
    | '/admin/achievements/$achievementId'
    | '/admin/achievements/create'
    | '/admin/announcements/$announcementId'
    | '/admin/announcements/create'
    | '/admin/capes/$capeId'
    | '/admin/capes/create'
    | '/admin/game-profiles/$profileId'
    | '/admin/issues/$issueId'
    | '/admin/plugin-credentials/$credentialId'
    | '/admin/skins/$skinId'
    | '/admin/skins/create'
    | '/admin/users/$userId'
    | '/user/issues/$issueId'
    | '/admin/achievements/'
    | '/admin/announcement-schedules/'
    | '/admin/announcements/'
    | '/admin/capes/'
    | '/admin/game-profiles/'
    | '/admin/issue-types/'
    | '/admin/issues/'
    | '/admin/plugin-credentials/'
    | '/admin/server-load/'
    | '/admin/servers/'
    | '/admin/skins/'
    | '/admin/titles/'
    | '/admin/users/'
    | '/user/capes/'
    | '/user/chat/'
    | '/user/commands/'
    | '/user/game-info/'
    | '/user/issues/'
    | '/user/my-titles/'
    | '/user/my/'
    | '/user/profile/'
    | '/user/profiles/'
    | '/user/skins/'
    | '/admin/users/$userId_/game-profiles'
    | '/admin/messages/chat/'
    | '/admin/messages/commands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  RulesRoute: typeof RulesRoute
  SetupRoute: typeof SetupRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/map': {
      id: '/user/map'
      path: '/map'
      fullPath: '/user/map'
      preLoaderRoute: typeof UserMapRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/setup/password': {
      id: '/setup/password'
      path: '/password'
      fullPath: '/setup/password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof SetupRoute
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/announcements/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/skins/': {
      id: '/user/skins/'
      path: '/skins'
      fullPath: '/user/skins/'
      preLoaderRoute: typeof UserSkinsIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profiles/': {
      id: '/user/profiles/'
      path: '/profiles'
      fullPath: '/user/profiles/'
      preLoaderRoute: typeof UserProfilesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile/': {
      id: '/user/profile/'
      path: '/profile'
      fullPath: '/user/profile/'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/my/': {
      id: '/user/my/'
      path: '/my'
      fullPath: '/user/my/'
      preLoaderRoute: typeof UserMyIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/my-titles/': {
      id: '/user/my-titles/'
      path: '/my-titles'
      fullPath: '/user/my-titles/'
      preLoaderRoute: typeof UserMyTitlesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/issues/': {
      id: '/user/issues/'
      path: '/issues'
      fullPath: '/user/issues/'
      preLoaderRoute: typeof UserIssuesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/game-info/': {
      id: '/user/game-info/'
      path: '/game-info'
      fullPath: '/user/game-info/'
      preLoaderRoute: typeof UserGameInfoIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/commands/': {
      id: '/user/commands/'
      path: '/commands'
      fullPath: '/user/commands/'
      preLoaderRoute: typeof UserCommandsIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/chat/': {
      id: '/user/chat/'
      path: '/chat'
      fullPath: '/user/chat/'
      preLoaderRoute: typeof UserChatIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/capes/': {
      id: '/user/capes/'
      path: '/capes'
      fullPath: '/user/capes/'
      preLoaderRoute: typeof UserCapesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/titles/': {
      id: '/admin/titles/'
      path: '/titles'
      fullPath: '/admin/titles/'
      preLoaderRoute: typeof AdminTitlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skins/': {
      id: '/admin/skins/'
      path: '/skins'
      fullPath: '/admin/skins/'
      preLoaderRoute: typeof AdminSkinsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servers/': {
      id: '/admin/servers/'
      path: '/servers'
      fullPath: '/admin/servers/'
      preLoaderRoute: typeof AdminServersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/server-load/': {
      id: '/admin/server-load/'
      path: '/server-load'
      fullPath: '/admin/server-load/'
      preLoaderRoute: typeof AdminServerLoadIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plugin-credentials/': {
      id: '/admin/plugin-credentials/'
      path: '/plugin-credentials'
      fullPath: '/admin/plugin-credentials/'
      preLoaderRoute: typeof AdminPluginCredentialsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issues/': {
      id: '/admin/issues/'
      path: '/issues'
      fullPath: '/admin/issues/'
      preLoaderRoute: typeof AdminIssuesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issue-types/': {
      id: '/admin/issue-types/'
      path: '/issue-types'
      fullPath: '/admin/issue-types/'
      preLoaderRoute: typeof AdminIssueTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game-profiles/': {
      id: '/admin/game-profiles/'
      path: '/game-profiles'
      fullPath: '/admin/game-profiles/'
      preLoaderRoute: typeof AdminGameProfilesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capes/': {
      id: '/admin/capes/'
      path: '/capes'
      fullPath: '/admin/capes/'
      preLoaderRoute: typeof AdminCapesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/': {
      id: '/admin/announcements/'
      path: '/announcements'
      fullPath: '/admin/announcements/'
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcement-schedules/': {
      id: '/admin/announcement-schedules/'
      path: '/announcement-schedules'
      fullPath: '/admin/announcement-schedules/'
      preLoaderRoute: typeof AdminAnnouncementSchedulesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements/': {
      id: '/admin/achievements/'
      path: '/achievements'
      fullPath: '/admin/achievements/'
      preLoaderRoute: typeof AdminAchievementsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/issues/$issueId': {
      id: '/user/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/user/issues/$issueId'
      preLoaderRoute: typeof UserIssuesIssueIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skins/create': {
      id: '/admin/skins/create'
      path: '/skins/create'
      fullPath: '/admin/skins/create'
      preLoaderRoute: typeof AdminSkinsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skins/$skinId': {
      id: '/admin/skins/$skinId'
      path: '/skins/$skinId'
      fullPath: '/admin/skins/$skinId'
      preLoaderRoute: typeof AdminSkinsSkinIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plugin-credentials/$credentialId': {
      id: '/admin/plugin-credentials/$credentialId'
      path: '/plugin-credentials/$credentialId'
      fullPath: '/admin/plugin-credentials/$credentialId'
      preLoaderRoute: typeof AdminPluginCredentialsCredentialIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issues/$issueId': {
      id: '/admin/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/admin/issues/$issueId'
      preLoaderRoute: typeof AdminIssuesIssueIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game-profiles/$profileId': {
      id: '/admin/game-profiles/$profileId'
      path: '/game-profiles/$profileId'
      fullPath: '/admin/game-profiles/$profileId'
      preLoaderRoute: typeof AdminGameProfilesProfileIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capes/create': {
      id: '/admin/capes/create'
      path: '/capes/create'
      fullPath: '/admin/capes/create'
      preLoaderRoute: typeof AdminCapesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capes/$capeId': {
      id: '/admin/capes/$capeId'
      path: '/capes/$capeId'
      fullPath: '/admin/capes/$capeId'
      preLoaderRoute: typeof AdminCapesCapeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/create': {
      id: '/admin/announcements/create'
      path: '/announcements/create'
      fullPath: '/admin/announcements/create'
      preLoaderRoute: typeof AdminAnnouncementsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements/$announcementId': {
      id: '/admin/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/admin/announcements/$announcementId'
      preLoaderRoute: typeof AdminAnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements/create': {
      id: '/admin/achievements/create'
      path: '/achievements/create'
      fullPath: '/admin/achievements/create'
      preLoaderRoute: typeof AdminAchievementsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/achievements/$achievementId': {
      id: '/admin/achievements/$achievementId'
      path: '/achievements/$achievementId'
      fullPath: '/admin/achievements/$achievementId'
      preLoaderRoute: typeof AdminAchievementsAchievementIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages/commands/': {
      id: '/admin/messages/commands/'
      path: '/messages/commands'
      fullPath: '/admin/messages/commands/'
      preLoaderRoute: typeof AdminMessagesCommandsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages/chat/': {
      id: '/admin/messages/chat/'
      path: '/messages/chat'
      fullPath: '/admin/messages/chat/'
      preLoaderRoute: typeof AdminMessagesChatIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId_/game-profiles': {
      id: '/admin/users/$userId_/game-profiles'
      path: '/users/$userId/game-profiles'
      fullPath: '/admin/users/$userId/game-profiles'
      preLoaderRoute: typeof AdminUsersUserIdGameProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAchievementsAchievementIdRoute: typeof AdminAchievementsAchievementIdRoute
  AdminAchievementsCreateRoute: typeof AdminAchievementsCreateRoute
  AdminAnnouncementsAnnouncementIdRoute: typeof AdminAnnouncementsAnnouncementIdRoute
  AdminAnnouncementsCreateRoute: typeof AdminAnnouncementsCreateRoute
  AdminCapesCapeIdRoute: typeof AdminCapesCapeIdRoute
  AdminCapesCreateRoute: typeof AdminCapesCreateRoute
  AdminGameProfilesProfileIdRoute: typeof AdminGameProfilesProfileIdRoute
  AdminIssuesIssueIdRoute: typeof AdminIssuesIssueIdRoute
  AdminPluginCredentialsCredentialIdRoute: typeof AdminPluginCredentialsCredentialIdRoute
  AdminSkinsSkinIdRoute: typeof AdminSkinsSkinIdRoute
  AdminSkinsCreateRoute: typeof AdminSkinsCreateRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminAchievementsIndexRoute: typeof AdminAchievementsIndexRoute
  AdminAnnouncementSchedulesIndexRoute: typeof AdminAnnouncementSchedulesIndexRoute
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
  AdminCapesIndexRoute: typeof AdminCapesIndexRoute
  AdminGameProfilesIndexRoute: typeof AdminGameProfilesIndexRoute
  AdminIssueTypesIndexRoute: typeof AdminIssueTypesIndexRoute
  AdminIssuesIndexRoute: typeof AdminIssuesIndexRoute
  AdminPluginCredentialsIndexRoute: typeof AdminPluginCredentialsIndexRoute
  AdminServerLoadIndexRoute: typeof AdminServerLoadIndexRoute
  AdminServersIndexRoute: typeof AdminServersIndexRoute
  AdminSkinsIndexRoute: typeof AdminSkinsIndexRoute
  AdminTitlesIndexRoute: typeof AdminTitlesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminUsersUserIdGameProfilesRoute: typeof AdminUsersUserIdGameProfilesRoute
  AdminMessagesChatIndexRoute: typeof AdminMessagesChatIndexRoute
  AdminMessagesCommandsIndexRoute: typeof AdminMessagesCommandsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAchievementsAchievementIdRoute: AdminAchievementsAchievementIdRoute,
  AdminAchievementsCreateRoute: AdminAchievementsCreateRoute,
  AdminAnnouncementsAnnouncementIdRoute: AdminAnnouncementsAnnouncementIdRoute,
  AdminAnnouncementsCreateRoute: AdminAnnouncementsCreateRoute,
  AdminCapesCapeIdRoute: AdminCapesCapeIdRoute,
  AdminCapesCreateRoute: AdminCapesCreateRoute,
  AdminGameProfilesProfileIdRoute: AdminGameProfilesProfileIdRoute,
  AdminIssuesIssueIdRoute: AdminIssuesIssueIdRoute,
  AdminPluginCredentialsCredentialIdRoute:
    AdminPluginCredentialsCredentialIdRoute,
  AdminSkinsSkinIdRoute: AdminSkinsSkinIdRoute,
  AdminSkinsCreateRoute: AdminSkinsCreateRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminAchievementsIndexRoute: AdminAchievementsIndexRoute,
  AdminAnnouncementSchedulesIndexRoute: AdminAnnouncementSchedulesIndexRoute,
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
  AdminCapesIndexRoute: AdminCapesIndexRoute,
  AdminGameProfilesIndexRoute: AdminGameProfilesIndexRoute,
  AdminIssueTypesIndexRoute: AdminIssueTypesIndexRoute,
  AdminIssuesIndexRoute: AdminIssuesIndexRoute,
  AdminPluginCredentialsIndexRoute: AdminPluginCredentialsIndexRoute,
  AdminServerLoadIndexRoute: AdminServerLoadIndexRoute,
  AdminServersIndexRoute: AdminServersIndexRoute,
  AdminSkinsIndexRoute: AdminSkinsIndexRoute,
  AdminTitlesIndexRoute: AdminTitlesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminUsersUserIdGameProfilesRoute: AdminUsersUserIdGameProfilesRoute,
  AdminMessagesChatIndexRoute: AdminMessagesChatIndexRoute,
  AdminMessagesCommandsIndexRoute: AdminMessagesCommandsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SetupRouteChildren {
  SetupPasswordRoute: typeof SetupPasswordRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupPasswordRoute: SetupPasswordRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserMapRoute: typeof UserMapRoute
  UserIndexRoute: typeof UserIndexRoute
  UserIssuesIssueIdRoute: typeof UserIssuesIssueIdRoute
  UserCapesIndexRoute: typeof UserCapesIndexRoute
  UserChatIndexRoute: typeof UserChatIndexRoute
  UserCommandsIndexRoute: typeof UserCommandsIndexRoute
  UserGameInfoIndexRoute: typeof UserGameInfoIndexRoute
  UserIssuesIndexRoute: typeof UserIssuesIndexRoute
  UserMyTitlesIndexRoute: typeof UserMyTitlesIndexRoute
  UserMyIndexRoute: typeof UserMyIndexRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
  UserProfilesIndexRoute: typeof UserProfilesIndexRoute
  UserSkinsIndexRoute: typeof UserSkinsIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserMapRoute: UserMapRoute,
  UserIndexRoute: UserIndexRoute,
  UserIssuesIssueIdRoute: UserIssuesIssueIdRoute,
  UserCapesIndexRoute: UserCapesIndexRoute,
  UserChatIndexRoute: UserChatIndexRoute,
  UserCommandsIndexRoute: UserCommandsIndexRoute,
  UserGameInfoIndexRoute: UserGameInfoIndexRoute,
  UserIssuesIndexRoute: UserIssuesIndexRoute,
  UserMyTitlesIndexRoute: UserMyTitlesIndexRoute,
  UserMyIndexRoute: UserMyIndexRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
  UserProfilesIndexRoute: UserProfilesIndexRoute,
  UserSkinsIndexRoute: UserSkinsIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  RulesRoute: RulesRoute,
  SetupRoute: SetupRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
