/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserDashboardRouteImport } from './routes/user/dashboard'
import { Route as SetupPasswordRouteImport } from './routes/setup/password'
import { Route as UserSkinsIndexRouteImport } from './routes/user/skins/index'
import { Route as UserProfilesIndexRouteImport } from './routes/user/profiles/index'
import { Route as UserProfileIndexRouteImport } from './routes/user/profile/index'
import { Route as UserMyIndexRouteImport } from './routes/user/my/index'
import { Route as UserIssuesIndexRouteImport } from './routes/user/issues/index'
import { Route as UserCapesIndexRouteImport } from './routes/user/capes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSkinsIndexRouteImport } from './routes/admin/skins/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminIssuesIndexRouteImport } from './routes/admin/issues/index'
import { Route as AdminIssueTypesIndexRouteImport } from './routes/admin/issue-types/index'
import { Route as AdminGameProfilesIndexRouteImport } from './routes/admin/game-profiles/index'
import { Route as AdminCapesIndexRouteImport } from './routes/admin/capes/index'
import { Route as UserIssuesIssueIdRouteImport } from './routes/user/issues/$issueId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminSkinsCreateRouteImport } from './routes/admin/skins/create'
import { Route as AdminSkinsSkinIdRouteImport } from './routes/admin/skins/$skinId'
import { Route as AdminIssuesIssueIdRouteImport } from './routes/admin/issues/$issueId'
import { Route as AdminGameProfilesProfileIdRouteImport } from './routes/admin/game-profiles/$profileId'
import { Route as AdminCapesCreateRouteImport } from './routes/admin/capes/create'
import { Route as AdminCapesCapeIdRouteImport } from './routes/admin/capes/$capeId'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SetupRoute,
} as any)
const UserSkinsIndexRoute = UserSkinsIndexRouteImport.update({
  id: '/skins/',
  path: '/skins/',
  getParentRoute: () => UserRoute,
} as any)
const UserProfilesIndexRoute = UserProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileIndexRoute = UserProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => UserRoute,
} as any)
const UserMyIndexRoute = UserMyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => UserRoute,
} as any)
const UserIssuesIndexRoute = UserIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => UserRoute,
} as any)
const UserCapesIndexRoute = UserCapesIndexRouteImport.update({
  id: '/capes/',
  path: '/capes/',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkinsIndexRoute = AdminSkinsIndexRouteImport.update({
  id: '/skins/',
  path: '/skins/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssuesIndexRoute = AdminIssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssueTypesIndexRoute = AdminIssueTypesIndexRouteImport.update({
  id: '/issue-types/',
  path: '/issue-types/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameProfilesIndexRoute = AdminGameProfilesIndexRouteImport.update({
  id: '/game-profiles/',
  path: '/game-profiles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapesIndexRoute = AdminCapesIndexRouteImport.update({
  id: '/capes/',
  path: '/capes/',
  getParentRoute: () => AdminRoute,
} as any)
const UserIssuesIssueIdRoute = UserIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkinsCreateRoute = AdminSkinsCreateRouteImport.update({
  id: '/skins/create',
  path: '/skins/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkinsSkinIdRoute = AdminSkinsSkinIdRouteImport.update({
  id: '/skins/$skinId',
  path: '/skins/$skinId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssuesIssueIdRoute = AdminIssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGameProfilesProfileIdRoute =
  AdminGameProfilesProfileIdRouteImport.update({
    id: '/game-profiles/$profileId',
    path: '/game-profiles/$profileId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCapesCreateRoute = AdminCapesCreateRouteImport.update({
  id: '/capes/create',
  path: '/capes/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCapesCapeIdRoute = AdminCapesCapeIdRouteImport.update({
  id: '/capes/$capeId',
  path: '/capes/$capeId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/setup/password': typeof SetupPasswordRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/capes/$capeId': typeof AdminCapesCapeIdRoute
  '/admin/capes/create': typeof AdminCapesCreateRoute
  '/admin/game-profiles/$profileId': typeof AdminGameProfilesProfileIdRoute
  '/admin/issues/$issueId': typeof AdminIssuesIssueIdRoute
  '/admin/skins/$skinId': typeof AdminSkinsSkinIdRoute
  '/admin/skins/create': typeof AdminSkinsCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/user/issues/$issueId': typeof UserIssuesIssueIdRoute
  '/admin/capes/': typeof AdminCapesIndexRoute
  '/admin/game-profiles/': typeof AdminGameProfilesIndexRoute
  '/admin/issue-types/': typeof AdminIssueTypesIndexRoute
  '/admin/issues/': typeof AdminIssuesIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/skins/': typeof AdminSkinsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/user/capes/': typeof UserCapesIndexRoute
  '/user/issues/': typeof UserIssuesIndexRoute
  '/user/my/': typeof UserMyIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
  '/user/profiles/': typeof UserProfilesIndexRoute
  '/user/skins/': typeof UserSkinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/setup/password': typeof SetupPasswordRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/user': typeof UserIndexRoute
  '/admin/capes/$capeId': typeof AdminCapesCapeIdRoute
  '/admin/capes/create': typeof AdminCapesCreateRoute
  '/admin/game-profiles/$profileId': typeof AdminGameProfilesProfileIdRoute
  '/admin/issues/$issueId': typeof AdminIssuesIssueIdRoute
  '/admin/skins/$skinId': typeof AdminSkinsSkinIdRoute
  '/admin/skins/create': typeof AdminSkinsCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/user/issues/$issueId': typeof UserIssuesIssueIdRoute
  '/admin/capes': typeof AdminCapesIndexRoute
  '/admin/game-profiles': typeof AdminGameProfilesIndexRoute
  '/admin/issue-types': typeof AdminIssueTypesIndexRoute
  '/admin/issues': typeof AdminIssuesIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/skins': typeof AdminSkinsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/user/capes': typeof UserCapesIndexRoute
  '/user/issues': typeof UserIssuesIndexRoute
  '/user/my': typeof UserMyIndexRoute
  '/user/profile': typeof UserProfileIndexRoute
  '/user/profiles': typeof UserProfilesIndexRoute
  '/user/skins': typeof UserSkinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/setup/password': typeof SetupPasswordRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/user/': typeof UserIndexRoute
  '/admin/capes/$capeId': typeof AdminCapesCapeIdRoute
  '/admin/capes/create': typeof AdminCapesCreateRoute
  '/admin/game-profiles/$profileId': typeof AdminGameProfilesProfileIdRoute
  '/admin/issues/$issueId': typeof AdminIssuesIssueIdRoute
  '/admin/skins/$skinId': typeof AdminSkinsSkinIdRoute
  '/admin/skins/create': typeof AdminSkinsCreateRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/user/issues/$issueId': typeof UserIssuesIssueIdRoute
  '/admin/capes/': typeof AdminCapesIndexRoute
  '/admin/game-profiles/': typeof AdminGameProfilesIndexRoute
  '/admin/issue-types/': typeof AdminIssueTypesIndexRoute
  '/admin/issues/': typeof AdminIssuesIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/skins/': typeof AdminSkinsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/user/capes/': typeof UserCapesIndexRoute
  '/user/issues/': typeof UserIssuesIndexRoute
  '/user/my/': typeof UserMyIndexRoute
  '/user/profile/': typeof UserProfileIndexRoute
  '/user/profiles/': typeof UserProfilesIndexRoute
  '/user/skins/': typeof UserSkinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/callback'
    | '/login'
    | '/setup'
    | '/user'
    | '/setup/password'
    | '/user/dashboard'
    | '/admin/'
    | '/user/'
    | '/admin/capes/$capeId'
    | '/admin/capes/create'
    | '/admin/game-profiles/$profileId'
    | '/admin/issues/$issueId'
    | '/admin/skins/$skinId'
    | '/admin/skins/create'
    | '/admin/users/$userId'
    | '/user/issues/$issueId'
    | '/admin/capes/'
    | '/admin/game-profiles/'
    | '/admin/issue-types/'
    | '/admin/issues/'
    | '/admin/profile/'
    | '/admin/skins/'
    | '/admin/users/'
    | '/user/capes/'
    | '/user/issues/'
    | '/user/my/'
    | '/user/profile/'
    | '/user/profiles/'
    | '/user/skins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/setup'
    | '/setup/password'
    | '/user/dashboard'
    | '/admin'
    | '/user'
    | '/admin/capes/$capeId'
    | '/admin/capes/create'
    | '/admin/game-profiles/$profileId'
    | '/admin/issues/$issueId'
    | '/admin/skins/$skinId'
    | '/admin/skins/create'
    | '/admin/users/$userId'
    | '/user/issues/$issueId'
    | '/admin/capes'
    | '/admin/game-profiles'
    | '/admin/issue-types'
    | '/admin/issues'
    | '/admin/profile'
    | '/admin/skins'
    | '/admin/users'
    | '/user/capes'
    | '/user/issues'
    | '/user/my'
    | '/user/profile'
    | '/user/profiles'
    | '/user/skins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/callback'
    | '/login'
    | '/setup'
    | '/user'
    | '/setup/password'
    | '/user/dashboard'
    | '/admin/'
    | '/user/'
    | '/admin/capes/$capeId'
    | '/admin/capes/create'
    | '/admin/game-profiles/$profileId'
    | '/admin/issues/$issueId'
    | '/admin/skins/$skinId'
    | '/admin/skins/create'
    | '/admin/users/$userId'
    | '/user/issues/$issueId'
    | '/admin/capes/'
    | '/admin/game-profiles/'
    | '/admin/issue-types/'
    | '/admin/issues/'
    | '/admin/profile/'
    | '/admin/skins/'
    | '/admin/users/'
    | '/user/capes/'
    | '/user/issues/'
    | '/user/my/'
    | '/user/profile/'
    | '/user/profiles/'
    | '/user/skins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/setup/password': {
      id: '/setup/password'
      path: '/password'
      fullPath: '/setup/password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof SetupRoute
    }
    '/user/skins/': {
      id: '/user/skins/'
      path: '/skins'
      fullPath: '/user/skins/'
      preLoaderRoute: typeof UserSkinsIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profiles/': {
      id: '/user/profiles/'
      path: '/profiles'
      fullPath: '/user/profiles/'
      preLoaderRoute: typeof UserProfilesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile/': {
      id: '/user/profile/'
      path: '/profile'
      fullPath: '/user/profile/'
      preLoaderRoute: typeof UserProfileIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/my/': {
      id: '/user/my/'
      path: '/my'
      fullPath: '/user/my/'
      preLoaderRoute: typeof UserMyIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/issues/': {
      id: '/user/issues/'
      path: '/issues'
      fullPath: '/user/issues/'
      preLoaderRoute: typeof UserIssuesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/capes/': {
      id: '/user/capes/'
      path: '/capes'
      fullPath: '/user/capes/'
      preLoaderRoute: typeof UserCapesIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skins/': {
      id: '/admin/skins/'
      path: '/skins'
      fullPath: '/admin/skins/'
      preLoaderRoute: typeof AdminSkinsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/profile'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issues/': {
      id: '/admin/issues/'
      path: '/issues'
      fullPath: '/admin/issues/'
      preLoaderRoute: typeof AdminIssuesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issue-types/': {
      id: '/admin/issue-types/'
      path: '/issue-types'
      fullPath: '/admin/issue-types/'
      preLoaderRoute: typeof AdminIssueTypesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game-profiles/': {
      id: '/admin/game-profiles/'
      path: '/game-profiles'
      fullPath: '/admin/game-profiles/'
      preLoaderRoute: typeof AdminGameProfilesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capes/': {
      id: '/admin/capes/'
      path: '/capes'
      fullPath: '/admin/capes/'
      preLoaderRoute: typeof AdminCapesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/issues/$issueId': {
      id: '/user/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/user/issues/$issueId'
      preLoaderRoute: typeof UserIssuesIssueIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skins/create': {
      id: '/admin/skins/create'
      path: '/skins/create'
      fullPath: '/admin/skins/create'
      preLoaderRoute: typeof AdminSkinsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skins/$skinId': {
      id: '/admin/skins/$skinId'
      path: '/skins/$skinId'
      fullPath: '/admin/skins/$skinId'
      preLoaderRoute: typeof AdminSkinsSkinIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issues/$issueId': {
      id: '/admin/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/admin/issues/$issueId'
      preLoaderRoute: typeof AdminIssuesIssueIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/game-profiles/$profileId': {
      id: '/admin/game-profiles/$profileId'
      path: '/game-profiles/$profileId'
      fullPath: '/admin/game-profiles/$profileId'
      preLoaderRoute: typeof AdminGameProfilesProfileIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capes/create': {
      id: '/admin/capes/create'
      path: '/capes/create'
      fullPath: '/admin/capes/create'
      preLoaderRoute: typeof AdminCapesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/capes/$capeId': {
      id: '/admin/capes/$capeId'
      path: '/capes/$capeId'
      fullPath: '/admin/capes/$capeId'
      preLoaderRoute: typeof AdminCapesCapeIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCapesCapeIdRoute: typeof AdminCapesCapeIdRoute
  AdminCapesCreateRoute: typeof AdminCapesCreateRoute
  AdminGameProfilesProfileIdRoute: typeof AdminGameProfilesProfileIdRoute
  AdminIssuesIssueIdRoute: typeof AdminIssuesIssueIdRoute
  AdminSkinsSkinIdRoute: typeof AdminSkinsSkinIdRoute
  AdminSkinsCreateRoute: typeof AdminSkinsCreateRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminCapesIndexRoute: typeof AdminCapesIndexRoute
  AdminGameProfilesIndexRoute: typeof AdminGameProfilesIndexRoute
  AdminIssueTypesIndexRoute: typeof AdminIssueTypesIndexRoute
  AdminIssuesIndexRoute: typeof AdminIssuesIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminSkinsIndexRoute: typeof AdminSkinsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCapesCapeIdRoute: AdminCapesCapeIdRoute,
  AdminCapesCreateRoute: AdminCapesCreateRoute,
  AdminGameProfilesProfileIdRoute: AdminGameProfilesProfileIdRoute,
  AdminIssuesIssueIdRoute: AdminIssuesIssueIdRoute,
  AdminSkinsSkinIdRoute: AdminSkinsSkinIdRoute,
  AdminSkinsCreateRoute: AdminSkinsCreateRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminCapesIndexRoute: AdminCapesIndexRoute,
  AdminGameProfilesIndexRoute: AdminGameProfilesIndexRoute,
  AdminIssueTypesIndexRoute: AdminIssueTypesIndexRoute,
  AdminIssuesIndexRoute: AdminIssuesIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminSkinsIndexRoute: AdminSkinsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SetupRouteChildren {
  SetupPasswordRoute: typeof SetupPasswordRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupPasswordRoute: SetupPasswordRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface UserRouteChildren {
  UserDashboardRoute: typeof UserDashboardRoute
  UserIndexRoute: typeof UserIndexRoute
  UserIssuesIssueIdRoute: typeof UserIssuesIssueIdRoute
  UserCapesIndexRoute: typeof UserCapesIndexRoute
  UserIssuesIndexRoute: typeof UserIssuesIndexRoute
  UserMyIndexRoute: typeof UserMyIndexRoute
  UserProfileIndexRoute: typeof UserProfileIndexRoute
  UserProfilesIndexRoute: typeof UserProfilesIndexRoute
  UserSkinsIndexRoute: typeof UserSkinsIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserDashboardRoute: UserDashboardRoute,
  UserIndexRoute: UserIndexRoute,
  UserIssuesIssueIdRoute: UserIssuesIssueIdRoute,
  UserCapesIndexRoute: UserCapesIndexRoute,
  UserIssuesIndexRoute: UserIssuesIndexRoute,
  UserMyIndexRoute: UserMyIndexRoute,
  UserProfileIndexRoute: UserProfileIndexRoute,
  UserProfilesIndexRoute: UserProfilesIndexRoute,
  UserSkinsIndexRoute: UserSkinsIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
